# Generated by Django 4.2.8 on 2024-01-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_winingbid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WiningBid',
            new_name='WinningBid',
        ),
    ]
